spring:
  datasource:
    hikari:
      max-lifetime: 5000000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.61.233:3306/azlm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Laobushide-1234


  redis:
    host: 124.71.61.233
    port: 6379
    password: mao159357!
    lettuce:
      pool:
        max-active: 5
        max-idle: 1
        min-idle: 1
        max-wait: 5000
    timeout: 300000


mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
# jwt配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名加盐
  secret: azmyzawdbaidb159
  #JWT过期时间(60*60*24*7) 半个小时 7天
  expiration: 18000
  # token头部
  tokenHead: 'Bearer '


