spring:


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.71.61.233:3306/azpm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Laobushide-1234

  redis:
    host: 124.71.61.233
    port: 6379
    password: mao159357!
    lettuce:
      pool:
        max-active: 5
        max-idle: 1
        min-idle: 1
        max-wait: 5000
    timeout: 30000

# 配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0